dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: "expleo"
    token:
      secure: "1ua5/WudW3/9zeey29UTPwFSeS/bFPnzZexJHgv53R8zjfidsu0p2CgIw8/I0foPnpWKUrrMUOUoZr3wKKzM9Yg8Uhr5yu8EjCtEHt+PLKkWbZeJ3VCttUg7paBI4pMGIq80A7F6PJUun9rim5n0RjZtYdCAS9Tjr9wMXrWnat1fk3zDEK7v00oZa+bWQSdPBmY3uTzeVD825ozFTaSbWjg+/PmYJVuh8acSIcJNb7HDB4X2sqEDdtWr9IIC8igbK448Gchr1kulbIjiYFfABR7FAEZoPCrCuIVk6PfETEMrT9JTd+LKCBvKswNUJpTcYJrXIfTqMCzp+jyKj6jUZFqGHQjDPYcBGYbigAtQWTDI7OIvf7x8kG28FNxRYpEE4b6drm1Guf5a1ayuif1qnFsH7K3sCUahkZlSpmkt8Lw8PoxSrrbRm5aVBDeEubNgQIR4iyU3eMgHe7LFWNiKY0hnIIpekHHtOl1uCg6dfapn0QVuo6u2Tj5OiA4c7muammhOOpt/uwJ0LcPO5UPoiOR03kaYvlXt1lU/ZPymHrEO/f+v5H7ErFliL6g/+OcDTyWy8iCwqw/4TO2jm7Bt497FFHGHJ28It7XGxDlNoPtYbJh1+32NmahsV+n92XLuu2/1Oeu4YMS0l4kHK63BO9XBv409qdD4cJILYzDKmKk="
jdk:
- openjdk11
script:
- mvn clean install sonar:sonar -Dsonar.projectKey=Expleo_SJP -Dmaven.test.failure.ignore=true
cache:
  directories:
  - "$HOME/.sonar/cache"
