dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: "expleo"
    token:
      secure: "kTDr2C71cVWfO2wsbLSCmpT8LITU56ECKoI0ulgSYTehpLh1sIpZVPbsxPndkGkAITxlMc5q58Xr59GPB5fI2+7aEKFAbaMdN/F2eKj6yM+vc+pfPeFaCMveBykx+cP7ivw0mkRc558UkDOyThKPua3hBXF2hTEQu/oiiCHo7m5kAazN9hut1Ooyorj4CZ7YZpcJvI29VtcwbMx7RSjAnNz4kKGBzMzcMB6Py99ooKiey+z5i9+EpHl0+rm5NZKymv18gL/Qf+kqo7d7JUvWEGXlMf82Xb/f60MLrmOdENyqargZt6LA53iqLz2xoFKFvamxl0ka1BxSK/EyAe3s382diqNIeT/uiO/505fGZMWLqRtit9WVpmM/RWgBvs5vH6DrHZbV7esFST4BENBo+OrurRKhIRMAqgv3LX7JhBuVQsjAohcISGI8ZJ3vM/pbtNVVVR4JSgvaYLasYztu/ANCQKPYTV72x5MnU1tT15oH+LXLt1ssNqvibBM7llYFHub+6gu/It8wDtqhrtrSeyaJbeyc9/y71lpxg9YnqntZEX6ybo/bLkPkysEy+kfqkVw64ZpujwC81ipr3ilNT/X4SIgoaYt9JH1O8MZF3H70egQQhhcFjKkz+xKbkgmJ1SAvXwvwnfRiuFUJTVVpbuzfy+OEBzyeREzF0MMrzqQ="
jdk:
- openjdk11
script:
- mvn clean install sonar:sonar -Dsonar.projectKey=SJP -Dmaven.test.failure.ignore=true
cache:
  directories:
  - "$HOME/.sonar/cache"
